Repository chingu-voyages/v38-geckos-team-04, pull requests merged in 2022-04, with the labels that each got.

#38 Feature: search form #29
  frontend/src/assets/search-icon.png
  frontend/src/components/SearchForm.js
  frontend/src/sass/abstract/variables.scss
  frontend/src/sass/components/main.scss
  frontend/src/sass/components/searchform.scss
Labels: enhancement, task, must_have

#39 Feature/backend setup
  backend/app.js
  backend/controller/appController.js
  backend/database/db.js
  backend/loremipsum
  backend/package-lock.json
  backend/package.json
  backend/routes/mainRoute.js
Labels: epic, must_have

#46 Create LICENSE
  LICENSE
Labels: documentation, nice_to_have

#49 Feature/create database
  .gitignore
  backend/app.js
  backend/controller/appController.js
  backend/database/db.js
  backend/model/project.js
  backend/package-lock.json
  backend/package.json
  backend/routes/api.js
  frontend/package.json
Labels: enhancement, task, must_have

#52 Feature/handle post request
  backend/controller/apiControl.js
  backend/package.json
  backend/routes/api.js
Labels: enhancement, must_have

#50 Refactor/readme
  README.md
Labels: documentation

#58 Feature/footer
  frontend/src/components/Footer.js
  frontend/src/components/Main.js
  frontend/src/components/SearchForm.js
  frontend/src/components/pages/About.js
  frontend/src/sass/base/typography.scss
  frontend/src/sass/components/footer.scss
Labels: task, nice_to_have

#59 Chore/update readme
  README.md
  assets/about.png
  assets/main.png
  assets/mobile.png
  assets/tablets_ipads.png
Labels: documentation, task, nice_to_have

#60 Remove placeholder text
  README.md
Labels: documentation, task, nice_to_have

#61 Update Main from Development
  .gitignore
  LICENSE
  README.md
  assets/about.png
  assets/main.png
  assets/mobile.png
  assets/tablets_ipads.png
  backend/app.js
  backend/controller/apiControl.js
  backend/model/project.js
  backend/package-lock.json
  backend/package.json
  backend/routes/api.js
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.js
  frontend/src/assets/search-icon.png
  frontend/src/components/Footer.js
  frontend/src/components/Header.js
  frontend/src/components/Main.js
  frontend/src/components/Navbar.js
  frontend/src/components/Result.js
  frontend/src/components/ResultsList.js
  frontend/src/components/SearchForm.js
  frontend/src/components/pages/About.js
  frontend/src/components/pages/Learn.js
  frontend/src/index.js
  frontend/src/sass/App.scss
  frontend/src/sass/abstract/mixins.scss
  frontend/src/sass/abstract/variables.scss
  frontend/src/sass/base/typography.scss
  frontend/src/sass/components/about.scss
  frontend/src/sass/components/footer.scss
  frontend/src/sass/components/header.scss
  frontend/src/sass/components/main.scss
  frontend/src/sass/components/navbar.scss
  frontend/src/sass/components/result.scss
  frontend/src/sass/components/resultslist.scss
  frontend/src/sass/components/searchform.scss
  frontend/src/sass/index.scss
Labels: must_have
